name = "BinaryTrees"
uuid = "8bc650ca-8ad6-11e9-0d37-8b534380b36e"
authors = ["Tobias Jagla <jagla@informatik.uni-leipzig.de>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
